"""
Constants for the robot.
"""
import math
from pathlib import Path

import wpimath.units

# Robot Physical Constants
ROBOT_WIDTH_INCHES = 29.0
ROBOT_LENGTH_INCHES = 29.0
WHEEL_DIAMETER_INCHES = 4.0

# Swerve Drive Constants
SWERVE_MAX_SPEED_FPS = 12.0  # Limited from 15.1 ft/s
SWERVE_MAX_ANGULAR_SPEED = math.pi  # 180 degrees/second

# CAN IDs - Sensors
PIGEON_ID = 21  # Pigeon 2.0 gyro

# CAN IDs - Swerve Drive
# Front Left Module
FL_DRIVE_MOTOR_ID = 10  # DOUBLE CHECK
FL_TURN_MOTOR_ID = 11 # DOUBLE CHECK
FL_CANCODER_ID = 19

# Front Right Module
FR_DRIVE_MOTOR_ID = 9 # DOUBLE CHECK
FR_TURN_MOTOR_ID = 8 # DOUBLE CHECK
FR_CANCODER_ID = 18

# Back Left Module
BL_DRIVE_MOTOR_ID = 12 # DOUBLE CHECK
BL_TURN_MOTOR_ID = 13 # DOUBLE CHECK
BL_CANCODER_ID = 20

# Back Right Module
BR_DRIVE_MOTOR_ID = 4 # DOUBLE CHECK
BR_TURN_MOTOR_ID = 5 # DOUBLE CHECK
BR_CANCODER_ID = 17

# CAN IDs - End Effector
CORAL_LEFT_MOTOR_ID = 7 # DOUBLE CHECK
CORAL_RIGHT_MOTOR_ID = 6 # DOUBLE CHECK
ALGAE_ARM_MOTOR_ID = 2 # DOUBLE CHECK
ALGAE_INTAKE_MOTOR_ID = 3 # DOUBLE CHECK

# CAN IDs - Elevator
LEFT_ELEVATOR_MOTOR_ID = 15  # NEO Vortex with SPARK FLEX
RIGHT_ELEVATOR_MOTOR_ID = 16  # NEO Vortex with SPARK FLEX

# Sensor IDs
# CORAL_ENCODER_ID = 19  # These don't have CAN ids
# ELEVATOR_ENCODER_ID = 20  # These don't have CAN ids
FRONT_RANGE_SENSOR_ID = 22 # DOUBLE CHECK
BACK_RANGE_SENSOR_ID = 23 # DOUBLE CHECK

# Elevator Heights (inches)
ELEVATOR_MIN_HEIGHT = 25.36  # Base position
ELEVATOR_L1_HEIGHT = 18.0
ELEVATOR_L2_HEIGHT = 31.875
ELEVATOR_L3_HEIGHT = 47.625
ELEVATOR_L4_HEIGHT = 72.0
ELEVATOR_MAX_HEIGHT = 70.86

# ALGAE Arm Angles (degrees)
ALGAE_ARM_REST_ANGLE = 0.0  # Straight down
ALGAE_ARM_WORKING_ANGLE = 40.0

# Controller Constants
DRIVER_CONTROLLER_PORT = 0
OPERATOR_CONTROLLER_PORT = 1
DEADBAND = 0.1  # 10% deadband on joysticks

# Motor Configuration
NEO_CURRENT_LIMIT = 40  # amps
NEO_VORTEX_CURRENT_LIMIT = 50  # amps for elevator motors

# PID Constants
# These will need tuning on the real robot
SWERVE_DRIVE_P = 0.1
SWERVE_DRIVE_I = 0.0
SWERVE_DRIVE_D = 0.0

SWERVE_TURN_P = 0.1
SWERVE_TURN_I = 0.0
SWERVE_TURN_D = 0.0

ELEVATOR_P = 0.1
ELEVATOR_I = 0.0
ELEVATOR_D = 0.0

CORAL_ARM_P = 0.1
CORAL_ARM_I = 0.0
CORAL_ARM_D = 0.0

ALGAE_ARM_P = 0.1
ALGAE_ARM_I = 0.0
ALGAE_ARM_D = 0.0 